### PR TITLE
Update with `eslint-config` and enforce import types

### PR DESCRIPTION
**Pull request by MicroFish91**
How does everyone feel about just adding this as an eslint rule so we don't have to think about whether something should be imported as a type or a value for optimization?

This should make it easier to enforce import types where we can essentially just run `eslint --fix`

### CODE REVIEW

**Comment by alexweininger** [comment]
Oh @bwateratmsft is going to love this. Yeah we should add this to our shared eslint config.

**Comment by MicroFish91** [comment]
Will update this next week using the shared eslint config*

**Comment by MicroFish91** [comment]
Updated!

**Review by nturinski — APPROVED** [review]

**Pull request merged**
